### ISSUE TITLE
mean and std value of DENSE dataset

### ISSUE THREAD

**Issue by Qizhi697** [arincbulgur/pytorch-WeatherNet#1]
https://github.com/arincbulgur/pytorch-WeatherNet/blob/8a39326ad8c2150ac5cb4dfa9b7ae2a4ef4a91e8/weathernet/datasets/dense.py#L82
Is this line calculating the average of distance and intensity? But the values ​​I calculate are around 6.15 and 0.005 respectively.
https://github.com/arincbulgur/pytorch-WeatherNet/blob/8a39326ad8c2150ac5cb4dfa9b7ae2a4ef4a91e8/weathernet/datasets/dense.py#L86
There is also the standard deviation of line 86, which is also very different from what I calculated. So I would like to ask if this value is the value of the DENSE dataset you calculated or the value of some other dataset?

**Comment by arincbulgur** [comment]
Yeah you are right I forgot to change them. Your mean values look correct.
